---
title: "question1"
author: "Sid"
output: pdf_document
---

```{r}
library(ggplot2)
library(tidyr)
library(viridis)
```


```{r}
data <- read.csv("data.csv",skip = 1)
data <- data %>% rename("Year" = "Year.to..31.March") %>% select("Year","Male","Female")
data
```


```{r}
data2 <- data %>%  gather(Sex, Area, 'Male':'Female')
data2
```




```{r}
ggplot(data = data2, aes(
  x = Year,
  y = Area,
  color = Sex,
  fill = Sex
)) +
  geom_bar(
    stat = "identity",
    position = "dodge",
    na.rm = TRUE,
    lwd = 1,
    width = 1
  ) +
  scale_fill_brewer() +
  scale_y_continuous(breaks = seq(0, 30, 5)) +
  xlab("") + theme_classic() +
  scale_x_continuous(breaks = seq(min(data2$Year), max(data2$Year) + 2 , by = 2)) +
  theme(
    axis.text.x = element_text(
      margin = margin(r = -1, unit = "cm"),
      vjust = -0.5,
      size = 9,
      angle = 45,
      hjust = 1.1
    ),
    axis.ticks = element_blank() ,
    
    legend.text = element_text(face = "italic", size = 9),
    legend.position = "bottom",
    legend.justification = "left"
  ) +
  xlab("") +
  ggtitle("Male vs Female Plot")
ggsave('data_plot.png')

```
